# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ee6f2b8dedf9e5c4c7c6cf0b58f9847a33951cf35fcc1e8c7a216b2d981eedeeb98139aa633adb09a5facbd0da87590b0c64ceb1d35c594fdd7e6b48cf2dd86

test:
  secret_key_base: 81b8282a70d0ef5bbd509c107a55838620c83383b749c448e7ae900ecb72410b522c39403f25dcfe32081cc5dc62f80acc71d2b907a305735396273471334f06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
